version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-alpine
    container_name: rabbitmq_payment
    environment:
      RABBITMQ_DEFAULT_USER: wise
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5674:5672"
      - "15674:15672"

  app:
    build: .
    container_name: payment_service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: wise
      SPRING_RABBITMQ_PASSWORD: admin
    ports:
      - "8081:8080"